# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
pop_culture = Category.create(category_name: 'Pop Culture')
 sports = Category.create(category_name: 'Sports')
 tazos = Category.create(category_name: 'Tazos')
woolworths = Category.create(category_name: 'Woolworths')
   Subcategory.create(subcategory_name: 'AFL', category: sports)
 Subcategory.create(subcategory_name: 'NRL', category: sports)
 Subcategory.create(subcategory_name: 'Basketball', category: sports)
 Subcategory.create(subcategory_name: 'Baseball', category: sports)
 Subcategory.create(subcategory_name: 'Cricket', category: sports)
 Subcategory.create(subcategory_name: 'Ninja Turtles', category: pop_culture)
 Subcategory.create(subcategory_name: 'Pokemon', category: pop_culture)
 Subcategory.create(subcategory_name: 'Final Fantasy', category: pop_culture)
 Subcategory.create(subcategory_name: 'Marvel Cards', category: pop_culture)
 Subcategory.create(subcategory_name: 'DC', category: pop_culture)
 Subcategory.create(subcategory_name: 'Yu-gi-oh', category: pop_culture)
 Subcategory.create(subcategory_name: 'Looney Tunes', category: tazos)
 Subcategory.create(subcategory_name: 'Cheetahs', category: tazos)
 Subcategory.create(subcategory_name: 'Star Wars', category: tazos)
 Subcategory.create(subcategory_name: 'Simpsons', category: tazos)
 Subcategory.create(subcategory_name: 'Space Jam', category: tazos)
 Subcategory.create(subcategory_name: 'Dreamworks', category: woolworths)
 Subcategory.create(subcategory_name: 'Disney Dominoes', category: woolworths)
 Subcategory.create(subcategory_name: 'Marvel Discs', category: woolworths)
